version: '3.8'

services:

  sandbox:
    build: .
    env_file: .env
    working_dir: /app
    command: python3 main.py --sandbox

  discord:
    build: .
    env_file: .env
    restart: unless-stopped 
    command: python3 main.py

