version: '3.8'

services:

  sandbox:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    working_dir: /app
    command: python3 main.py --sandbox

  discord:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    restart: unless-stopped 
    command: python3 main.py

